-- Application role subject to RLS (POSTGRES_USER is a superuser and bypasses RLS)
DO $$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'sandiwa_app') THEN
    CREATE ROLE sandiwa_app LOGIN PASSWORD '__SANDIWA_APP_PASSWORD__' NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE;
  ELSE
    ALTER ROLE sandiwa_app WITH PASSWORD '__SANDIWA_APP_PASSWORD__';
  END IF;
END $$;

DO $$
BEGIN
  EXECUTE format('GRANT CONNECT ON DATABASE %I TO sandiwa_app', current_database());
END $$;

GRANT USAGE ON SCHEMA public TO sandiwa_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO sandiwa_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO sandiwa_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO sandiwa_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO sandiwa_app;
